### ISSUE TITLE
The Terraform Migration Epic

### ISSUE THREAD

**Issue by nyarly** [hackforla/incubator#20]
### Overview
DevOps needs to complete a migration from Terragrunt to Terraform.

The most important reason being, Terragrunt has been made largely superfluous by
features added to Terraform, and as a result is not well known in the larger Ops community.
Better to be learning and teaching Terraform, which is an industry standard.

More subtly but just as important, Terraform has lots of support in the larger community.
There's lots of tools, documentation, and general experience with Terraform that 
Terragrunt simply can't compare to. It's even possible that Hack for LA volunteers
will have existing experience with Terraform and be able to contribute right away.

The general principle here, and moreso that other organizations, is Hack for LA should consider
the available expertise for their tools as a very high priority. In the case of Infrastructure as Code, there are many, many toolsets available, but Terraform is one of a small set of clear winners in terms of broad adoption.

This process has already started (c.f. https://github.com/hackforla/incubator/blob/main/documentation/terraform-migrate-project.md),
but the approach used for Terragrunt means that project owners need to help contribute to the migration process. In particular, there are `project.hcl` files that have been used to store secret data, and are managed by the owners of particular projects.

### Action Items
The following projects need to be migrated:

- [ ] ballotnav-api
- [ ] civictechindex-api
- [ ] home-unite-us-api
- [ ] people-depot-backend
- [ ] vrms-backend
- [ ] vrms-client

- [ ] Issues need to be created on each of the above Github repos, and noted here.
- [ ] Responsible parties for those projects need to be identified and noted here.

### Resources/Instructions

A guide to this process can be found in this projects [documentation/] directory.

Please direct questions about this project or requests for aid (which are expected!) to the #ops channel - feel free to ping @Judson(github: @nyarly) or @JasonEb

**Comment by nyarly** [comment]
It wasn't clear to me what repos are associated with `civictechindex-api` - there are several repos with names like "Civic Tech"...

People Depot was the test case.

**Comment by nyarly** [comment]
With Jason's help, discovered that CTI has its own organization on github.

**Comment by robinglov** [comment]
Taking this issue out of icebox to prioritize migrating remaining projects over to use terraform.

**Comment by ExperimentsInHonesty** [comment]
Are these issues ready to work or do they need updating since Judson made them?

**Comment by ExperimentsInHonesty** [comment]
- Notes from meeting. Transfer the issues back from the teams and put them in icebox for when issue #20 is completed.

**Comment by ale210** [comment]
I need to rewrite this issue using tasks that we have for incubator V2
