### ISSUE TITLE
IBT: PM Introductory

### ISSUE THREAD

**Issue by madcharlie02** [hackforla/incubator#21]
### Overview
This issue tracks the agenda for our weekly meetings

#### Issue Template
```
## [Date ]  Meeting Agenda

### Prework to prep for meeting
- [ ] #

### Recurring items: Happens on the ________ meeting
 - [ ] review any issues that are in the [new issue approval column]
 - [ ] Accountability and Support Check.
    - [ ] Review assignments for each Team member
       - [ ] [Name of Person]
- [ ] finish adding labels to the issue that are still missing them (see audit links above)
- [ ] review issues with [epic label] and define how to break down further
- [ ] Review to see if there are any members to Onboard or Offboard 
      - [ ]  #

### New Items
- [ ] 
- [ ] Carry over Items to next meeting that don't get addressed

### FYIs
-

### Notes from Meeting

### Task Items
```

### Links to other agenda issues for your team 
(so that you can easily post on their agendas items that come up at yours)

### Previous Meetings (link to each comment with the date)

**Comment by madcharlie02** [comment]
## 2023-10-01   Meeting Agenda

### Prework to prep for meeting
- [ ] #

### Recurring items: 
 - [ ] review any issues that are in the [new issue approval column]
 - [ ] Accountability and Support Check.
    - [ ] Review assignments for each Team member
       - [ ] [Name of Person]
- [ ] finish adding labels to the issue that are still missing them (see audit links above)
- [ ] review issues with [epic label] and define how to break down further
- [ ] Review to see if there are any members to Onboard or Offboard 
      - [ ]  #

### New Items
- [ ] 
- [ ] Carry over Items to next meeting that don't get addressed

### FYIs
-

### Notes from Meeting

### Task Items

**Comment by madcharlie02** [comment]
## 2023-10-08  Meeting Agenda

### Prework to prep for meeting
- [ ] #

### Recurring items: Happens on the ________ meeting
 - [ ] review any issues that are in the [new issue approval column]
 - [ ] Accountability and Support Check.
    - [ ] Review assignments for each Team member
       - [ ] [Name of Person]
- [ ] finish adding labels to the issue that are still missing them (see audit links above)
- [ ] review issues with [epic label] and define how to break down further
- [ ] Review to see if there are any members to Onboard or Offboard 
      - [ ]  #

### New Items
- [ ] 
- [ ] Carry over Items to next meeting that don't get addressed

### FYIs
-

### Notes from Meeting

### Task Items

- [ ] PM Training
- [ ] Update IBT wiki page

**Comment by ExperimentsInHonesty** [comment]
Item for todays agenda
- remove next weeks tuesday meeting, it conflicts with onboarding

**Comment by ExperimentsInHonesty** [comment]
Agenda

**Comment by madcharlie02** [comment]
## [Date ]  Meeting Agenda

### Prework to prep for meeting
- [ ] #24 

### Recurring items
 - [ ] review any issues that are in the [new issue approval column](https://github.com/hackforla/incubator/projects/1#column-19648741)
 - [ ] reviewing any issues in the [questions and review column](https://github.com/hackforla/incubator/projects/1#column-19648744)
 - [ ] Accountability and Support Check.
    - [ ] Review assignments for each Team member
       - [ ] [Charles](https://github.com/hackforla/incubator/issues/assigned/madcharlie02)
       - [ ] [Bonnie](https://github.com/hackforla/incubator/issues/assigned/ExperimentsInHonesty)
       - [ ] [Jason](https://github.com/hackforla/incubator/issues/assigned/JasonEb)
       - [ ] [Judson](https://github.com/hackforla/incubator/issues/assigned/nyarly)
- [ ] finish adding labels to the issue that are still missing them (see audit links above)
- [ ] review issues with [epic label](https://github.com/hackforla/incubator/issues?q=is%3Aopen+is%3Aissue+label%3Aepic) and define how to break down further
- [ ] Review to see if there are any members to Onboard or Offboard 
      - [ ]  #

### New Items
- [ ] 
- [ ] Carry over Items to next meeting that don't get addressed

### FYIs
-

### Notes from Meeting

### Task Items
- Make an onboarding and offboarding issue

**Comment by madcharlie02** [comment]
## 2023-11-18  Meeting Agenda

### Prework to prep for meeting
- [ ] #24 

### Recurring items
 - [ ] review any issues that are in the [new issue approval column](https://github.com/hackforla/incubator/projects/1#column-19648741)
 - [ ] reviewing any issues in the [questions and review column](https://github.com/hackforla/incubator/projects/1#column-19648744)
 - [ ] Accountability and Support Check.
    - [ ] Review assignments for each Team member
       - [ ] [Charles](https://github.com/hackforla/incubator/issues/assigned/madcharlie02)
       - [ ] [Bonnie](https://github.com/hackforla/incubator/issues/assigned/ExperimentsInHonesty)
       - [ ] [Jason](https://github.com/hackforla/incubator/issues/assigned/JasonEb)
       - [ ] [Judson](https://github.com/hackforla/incubator/issues/assigned/nyarly)
- [ ] finish adding labels to the issue that are still missing them (see audit links above)
- [ ] review issues with [epic label](https://github.com/hackforla/incubator/issues?q=is%3Aopen+is%3Aissue+label%3Aepic) and define how to break down further
- [ ] Review to see if there are any members to Onboard or Offboard 
      - [ ]  #

### New Items
- [ ] https://hackforla.slack.com/archives/CV7QGL66B/p1697078455017279
- [ ] Carry over Items to next meeting that don't get addressed

### FYIs
-

### Notes from Meeting

### Task Items
- Make an onboarding and offboarding issue

**Comment by robinglov** [comment]
## [Date ]  Meeting Agenda

### Prework to prep for meeting
- [ ] #24 

### Recurring items
 - [ ] review any issues that are in the [new issue approval column](https://github.com/hackforla/incubator/projects/1#column-19648741)
 - [ ] reviewing any issues in the [questions and review column](https://github.com/hackforla/incubator/projects/1#column-19648744)
 - [ ] Accountability and Support Check.
    - [ ] Review assignments for each Team member
       - [ ] [Charles](https://github.com/hackforla/incubator/issues/assigned/madcharlie02)
       - [ ] [Bonnie](https://github.com/hackforla/incubator/issues/assigned/ExperimentsInHonesty)
       - [ ] [Jason](https://github.com/hackforla/incubator/issues/assigned/JasonEb)
       - [ ] [Judson](https://github.com/hackforla/incubator/issues/assigned/nyarly)
- [ ] finish adding labels to the issue that are still missing them (see audit links above)
- [ ] review issues with [epic label](https://github.com/hackforla/incubator/issues?q=is%3Aopen+is%3Aissue+label%3Aepic) and define how to break down further
- [ ] Review to see if there are any members to Onboard or Offboard 
      - [ ]  #

### New Items
- [ ] Review IAM notes from Ops meeting and to-do items
- [ ] AWS Add user demo for people 
- [ ] Carry over Items to next meeting that don't get addressed

### FYIs
-

### Notes from Meeting
100% Infrastructure as code. Challenge will be controlling merge teams. 
### Task Items
- Make an onboarding and offboarding issue

**Comment by robinglov** [comment]
## 2024-02-04  Meeting Agenda

### Prework to prep for meeting
- [ ] #24 

### Recurring items
 - [ ] review any issues that are in the [new issue approval column](https://github.com/hackforla/incubator/projects/1#column-19648741)
 - [ ] reviewing any issues in the [questions and review column](https://github.com/hackforla/incubator/projects/1#column-19648744)
 - [ ] Accountability and Support Check.
    - [ ] Review assignments for each Team member
       - [ ] [Charles](https://github.com/hackforla/incubator/issues/assigned/madcharlie02)
       - [ ] [Bonnie](https://github.com/hackforla/incubator/issues/assigned/ExperimentsInHonesty)
       - [ ] [Jason](https://github.com/hackforla/incubator/issues/assigned/JasonEb)
       - [ ] [Judson](https://github.com/hackforla/incubator/issues/assigned/nyarly)
- [ ] finish adding labels to the issue that are still missing them (see audit links above)
- [ ] review issues with [epic label](https://github.com/hackforla/incubator/issues?q=is%3Aopen+is%3Aissue+label%3Aepic) and define how to break down further
- [ ] Review to see if there are any members to Onboard or Offboard 
      - [ ]  #

### New Items
- [ ] #47 - finish links
- [ ] Carry over Items to next meeting that don't get addressed

### FYIs
-

### Notes from Meeting

### Task Items
-

**Comment by robinglov** [comment]
## 2024-2-11  Meeting Agenda

### Prework to prep for meeting
- [ ] #24 

### Recurring items
 - [ ] review any issues that are in the [new issue approval column](https://github.com/hackforla/incubator/projects/1#column-19648741)
 - [ ] reviewing any issues in the [questions and review column](https://github.com/hackforla/incubator/projects/1#column-19648744)
- [ ] finish adding labels to the issue that are still missing them (see audit links above)

### New Items
- [ ] Add Charles
- [ ] Carry over Items to next meeting that don't get addressed

### FYIs
-

### Notes from Meeting

### Task Items
- Make an onboarding and offboarding issue

**Comment by ExperimentsInHonesty** [comment]
## 2024-02-18 Meeting Agenda

### Prework to prep for meeting
- [ ] #24 

### Recurring items
 - [ ] review any issues that are in the [new issue approval column](https://github.com/hackforla/incubator/projects/1#column-19648741)
 - [ ] reviewing any issues in the [questions and review column](https://github.com/hackforla/incubator/projects/1#column-19648744)
 - [ ] Accountability and Support Check.
    - [ ] Review assignments for each Team member
       - [ ] [Charles](https://github.com/hackforla/incubator/issues/assigned/madcharlie02)
       - [ ] [Bonnie](https://github.com/hackforla/incubator/issues/assigned/ExperimentsInHonesty)
       - [ ] [Jason](https://github.com/hackforla/incubator/issues/assigned/JasonEb)
       - [ ] [Judson](https://github.com/hackforla/incubator/issues/assigned/nyarly)
- [ ] finish adding labels to the issue that are still missing them (see audit links above)
- [ ] review issues with [epic label](https://github.com/hackforla/incubator/issues?q=is%3Aopen+is%3Aissue+label%3Aepic) and define how to break down further
- [ ] Review to see if there are any members to Onboard or Offboard 
      - [ ]  #27 

### New Items
- [ ] Check to see if all the onboarding / offboarding issues got made.  If not, define what is needed under tasks
- [ ] Carry over Items to next meeting that don't get addressed

### FYIs
-

### Notes from Meeting
- Under the last agenda, there was an FYI, Team page is updated, I am assuming it's this: https://github.com/hackforla/incubator/wiki/The-Team, but it's not in the right format. The [IBT roster](https://docs.google.com/spreadsheets/d/1kMuw8UWj3C4IebTwAmW3GluK2E1WcmUhsvyug0-kU_Y/edit#gid=0) needs some additional pages, and from that, we can copy the info to the team page.
- 

### Task Items
-Update roster, using Internship as example

**Comment by ExperimentsInHonesty** [comment]
## 2024-02-25  Meeting Agenda

### Prework to prep for meeting
- [ ] #24 

### Recurring items
 - [ ] review any issues that are in the [new issue approval column](https://github.com/hackforla/incubator/projects/1#column-19648741)
 - [ ] reviewing any issues in the [questions and review column](https://github.com/hackforla/incubator/projects/1#column-19648744)
 - [ ] Accountability and Support Check.
    - [ ] Review assignments for each Team member
       - [ ] [Charles](https://github.com/hackforla/incubator/issues/assigned/madcharlie02)
       - [ ] [Bonnie](https://github.com/hackforla/incubator/issues/assigned/ExperimentsInHonesty)
       - [ ] [Jason](https://github.com/hackforla/incubator/issues/assigned/JasonEb)
       - [ ] [Judson](https://github.com/hackforla/incubator/issues/assigned/nyarly)
       - [ ] [Robin](https://github.com/hackforla/incubator/issues/assigned/robinglov)
- [ ] finish adding labels to the issue that are still missing them (see audit links above)
- [ ] review issues with [epic label](https://github.com/hackforla/incubator/issues?q=is%3Aopen+is%3Aissue+label%3Aepic) and define how to break down further
- [ ] Review to see if there are any members to Onboard or Offboard 
      - [ ]  #27 

### New Items
- [ ] BW: Run both Charles and Robin through the onboarding product issue https://github.com/hackforla/incubator/issues/47 to make sure they have all the right permission and access and that we don't need any updates to the product onboarding checklist template.
- [ ] BW: we need to reach out to everone on the IBT roster](https://docs.google.com/spreadsheets/d/1kMuw8UWj3C4IebTwAmW3GluK2E1WcmUhsvyug0-kU_Y/edit#gid=0), via slack, with an update, and find out who is still on the team, so that we can mark some people as inactive.  This will allow us to publish this page https://github.com/hackforla/incubator/wiki/The-Team.
- [ ] Do the tasks left over from last meeting if they are not yet checked off.
- [ ] Carry over Items to next meeting that don't get addressed

### FYIs
- I have built a tab on the roster for Current Team and Former team, and I can show you how to update the wiki page when we are ready.

### Notes from Meeting

### Task Items

**Comment by ExperimentsInHonesty** [comment]
## 2024-03-03 Meeting Agenda

### Prework to prep for meeting
- [ ] #24 

### Recurring items
 - [ ] review any issues that are in the [new issue approval column](https://github.com/hackforla/incubator/projects/1#column-19648741)
 - [ ] reviewing any issues in the [questions and review column](https://github.com/hackforla/incubator/projects/1#column-19648744)
 - [ ] Accountability and Support Check.
    - [ ] Review assignments for each Team member
       - [ ] [Charles](https://github.com/hackforla/incubator/issues/assigned/madcharlie02)
       - [ ] [Bonnie](https://github.com/hackforla/incubator/issues/assigned/ExperimentsInHonesty)
       - [ ] [Jason](https://github.com/hackforla/incubator/issues/assigned/JasonEb)
       - [ ] [Judson](https://github.com/hackforla/incubator/issues/assigned/nyarly)
       - [ ] [Robin](https://github.com/hackforla/incubator/issues/assigned/robinglov)
- [ ] finish adding labels to the issue that are still missing them (see audit links above)
- [ ] review issues with [epic label](https://github.com/hackforla/incubator/issues?q=is%3Aopen+is%3Aissue+label%3Aepic) and define how to break down further
- [ ] Review to see if there are any members to Onboard or Offboard 
      - [ ]  #27 

### New Items
- [ ] 
- [ ] Carry over Items to next meeting that don't get addressed

### FYIs
-

### Notes from Meeting

### Task Items

**Comment by robinglov** [comment]
## [Date ]  2024-03-10

### Prework to prep for meeting
- [ ] #24 

### Recurring items
 - [ ] review any issues that are in the [new issue approval column](https://github.com/hackforla/incubator/projects/1#column-19648741)
 - [ ] reviewing any issues in the [questions and review column](https://github.com/hackforla/incubator/projects/1#column-19648744)
 - [ ] Accountability and Support Check.
    - [ ] Review assignments for each Team member
       - [ ] [Charles](https://github.com/hackforla/incubator/issues/assigned/madcharlie02)
       - [ ] [Bonnie](https://github.com/hackforla/incubator/issues/assigned/ExperimentsInHonesty)
       - [ ] [Jason](https://github.com/hackforla/incubator/issues/assigned/JasonEb)
       - [ ] [Judson](https://github.com/hackforla/incubator/issues/assigned/nyarly)
       - [ ] [Robin](https://github.com/hackforla/incubator/issues/assigned/robinglov)
       - [ ] [Jenny](https://github.com/hackforla/incubator/issues/assigned/jennyc910)
- [ ] finish adding labels to the issue that are still missing them (see audit links above)
- [ ] review issues with [epic label](https://github.com/hackforla/incubator/issues?q=is%3Aopen+is%3Aissue+label%3Aepic) and define how to break down further
- [ ] Review to see if there are any members to Onboard or Offboard 
      - [ ]  #27 

### New Items
 - [ ] BW: Run both Charles and Robin through the onboarding product issue https://github.com/hackforla/incubator/issues/47 to make sure they have all the right permission and access and that we don't need any updates to the product onboarding checklist template.

### FYIs


### Notes from Meeting

- 

### Task Items

**Comment by jennyc910** [comment]
## 2024-04-14  Meeting Agenda

### Prework to prep for meeting
- [ ] #24 

### Recurring items
 - [ ] review any issues that are in the [new issue approval column](https://github.com/hackforla/incubator/projects/1#column-19648741)
 - [ ] reviewing any issues in the [questions and review column](https://github.com/hackforla/incubator/projects/1#column-19648744)
 - [ ] Accountability and Support Check.
    - [ ] Review assignments for each Team member
       - [ ] [Charles](https://github.com/hackforla/incubator/issues/assigned/madcharlie02)
       - [ ] [Bonnie](https://github.com/hackforla/incubator/issues/assigned/ExperimentsInHonesty)
       - [ ] [Jason](https://github.com/hackforla/incubator/issues/assigned/JasonEb)
       - [ ] [Judson](https://github.com/hackforla/incubator/issues/assigned/nyarly)
       - [ ] [Robin](https://github.com/hackforla/incubator/issues/assigned/robinglov)
       - [ ] [Jenny](https://github.com/hackforla/incubator/issues/assigned/jennyc910)
- [ ] finish adding labels to the issue that are still missing them (see audit links above)
- [ ] review issues with [epic label](https://github.com/hackforla/incubator/issues?q=is%3Aopen+is%3Aissue+label%3Aepic) and define how to break down further
- [ ] Review to see if there are any members to Onboard or Offboard 
      - [ ]  #27 

### New Items
- [ ] Check on [AWS Tutorial Update](https://github.com/hackforla/ops/issues/111)

### FYIs
-

### Notes from Meeting

### Task Items

**Comment by ExperimentsInHonesty** [comment]
Closing this issue because we no longer have Incubator as a separate team.
