### ISSUE TITLE
Create Milestones for Incubator Project

### ISSUE THREAD

**Issue by madcharlie02** [hackforla/incubator#23]
### Overview
We need to create a roadmap that includes the milestone list to help with product prioritisation, project monitoring and for the team to know what each task builds up to.

### Action Items

- [x] Create a new spreadsheet
- [x] Copy the first milestones from OCS
- [x] Add in team workflow and planning

### Resources/Instructions
[Guides Project Roadmap](https://docs.google.com/spreadsheets/d/1xYUlIKsfE2-CeExIQ8i3oLD8pC7hjMTPM2YLSMFA8_s/edit#gid=0)
[OCS Project Roadmap](https://docs.google.com/spreadsheets/d/163RPNWPhkeah2OvGCqjByMukYduXk66XY7ZpcpLCzXU/edit#gid=617281993)

[epics from Leads Agenda
](https://github.com/hackforla/incubator/issues/22#issuecomment-1745995018)

Link to [IBT: Roadmap](https://docs.google.com/spreadsheets/d/1XxdvzKAeusWTamfzUtajX2ZQesIZOIMWAiz7TfTEt7I/edit#gid=0) Spreadsheet

[Milestone Page](https://github.com/hackforla/incubator/milestones?direction=asc&sort=title&state=open)

**Comment by madcharlie02** [comment]
Milestones have been added to the milestone page
