### ISSUE TITLE
Introduce a Pre-Deployment Checklist for Incubator 

### ISSUE THREAD

**Issue by JasonEb** [hackforla/incubator#25]
### Dependency
- A new issue being created and closed that has deploying from scratch to incubator using terraform.

### Overview
- See related issue https://github.com/hackforla/incubator/issues/11

We need a pre deployment checklist for incubator so that HfLA projects have documentation that lets them know what they need to do to prepare to get on the Ops calendar for assistance in deploying their application onto our incubator platform

### Action Items
- [ ] Define the leanest requirements for deploying on Incubator
- [ ] Discuss with #ops CoP current and previous deployments
- [ ] Draft Checklist
- [ ] Publish Checklist on Ops / Wiki

### Resources/Instructions
- [Ops wiki](https://github.com/hackforla/ops/wiki)
- Migration Instructions: https://github.com/hackforla/incubator/blob/main/documentation/terraform-migrate-project.md

####  Checklist [draft]
- [ ] Docker Image
- [ ] Project.hcl
- [ ] AWS Authentication

**Comment by ExperimentsInHonesty** [comment]
may not be relevant, or a its a duplicate or needs to be re written.
