### ISSUE TITLE
IBT: Onboard & Offboard: Team Members

### ISSUE THREAD

**Issue by madcharlie02** [hackforla/incubator#27]
### Overview
REPLACE THIS TEXT -Text here that clearly states the purpose of this issue in 2 sentences or less.

### Action Items

```
#### Onboard [replace with name and role]
- [ ] Slack channel membership
  - [ ] ```#internship```
  - [ ] ```#interns``` (if necessary)
     - [ ] not needed
- [ ] Add to Google calendar invites
   - [ ] Tuesday Design System Meeting
      - [ ] not needed 
   - [ ] Tuesday BA meeting (if necessary)
      - [ ] not needed
   - [ ] Tuesday UX Research meeting (if necessary)
      - [ ] not needed
   - [ ] Thursday All-team meeting
- [ ] Google Drive
   - [ ] Add to drive as Contributor
- [ ] Roster
  - [ ] Send [link](https://docs.google.com/spreadsheets/d/1G6IgfvTdfnJRPbqxPkqfQ3dOSf8nvYqy0JVifhY6QdU/edit#gid=2054073727)
  - [ ] Team member adds themselves
  - [ ] Check for Public
- [ ] GitHub _- if it asks you to open up an authenticator app, use your GitHub password instead_
     - [ ] Add to team write team
     - [ ] Add to base/read team
     - [ ] Confirm that their name is on their Github  
     - [ ] Assign them to the issue #101, add them to role call and accountability check 
- [ ] Figma
  - [ ] invite
  - [ ] acceptance
- [ ] 1password
     - [ ] invitation (if necessary)
       - [ ] not needed 
     - [ ] acceptance
     - [ ] add to vaults
       - [ ] Internship program (if necessary)
         - [ ] not needed 
       - [ ] Internship-UX  (if necessary)
         - [ ] not needed 
- [ ] Update team page on Wiki
   - [How to activate-inactivate team members from roster and wiki](https://github.com/hackforla/internship/wiki/How-to-activate-inactivate-team-members-from-roster-and-wiki)
- [ ] Add to email address(s)
   - [ ] internship@hackforla.org (if necessary)
      - [ ] not needed
   - [ ] internship-ux@hackforla.org (if necessary)
      - [ ] not needed
- [ ] Social Media Accounts with role assignment
   - [ ] Facebook (if necessary)
      - [ ] not needed
- [ ] Train how to 
   - [ ] login to team email account (if necessary)
      - [ ] not needed
   - [ ] setup chrome shortcut for adding to desktop (if necessary)
      - [ ] not needed

```

```
#### Offboard [replace with name and role]
- [ ] Remove from Google calendar invite
   - [ ] Monday PM meeting
   - [ ] Tuesday BA meeting
   - [ ] Tuesday UX Research meeting
   - [ ] Wednesday PM meeting (ad-hoc)
   - [ ] Thursday All-team meeting
 - [ ] 1password setup
    - [ ] ask an admin or in #admin channel on slack to remove team members from team vaults
       - [ ] Internship program
       - [ ] Internship - UI/UX
- [ ] Internship shared Google Drive
   - [ ] demote to viewer
- [ ] Internship - PII Google Drive
   - [ ] remove access to the drive
- [ ] Roster
  - [ ] mark as inactive
- [ ] GitHub
     - [ ] remove from write team
     - [ ] Un Assign them to the issue #101, remove them from role call and accountability check 
     - [ ] Un Assign from any other Meeting Agenda issues, remove them from role call and accountability check 
     - [ ] Check their Assignment status on the Issue tab, to make sure they are no longer assigned to any issues
- [ ] Figma
  - [ ] remove from team
- [ ] Help them delete the desktop shortcut to email address if they made one
- [ ] Remove from email address(s)
   - [ ] internship@hackforla.org
   - [ ] internship-ux@hackforla.org
- [ ] Remove from Social Media Accounts with role assignment
   - [ ] Facebook
- [ ] Update Wiki
  - [How to activate-inactivate team members from roster and wiki](https://github.com/hackforla/internship/wiki/How-to-activate-inactivate-team-members-from-roster-and-wiki)
```

### Resources/Instructions
REPLACE THIS TEXT -If there is a website which has documentation that helps with this issue provide the link(s) here.

**Comment by madcharlie02** [comment]
#### Onboard Robin - PM 2023-11-12
- [ ] Slack channel membership
  - [ ] ```#Ops```
     - [ ] not needed
- [ ] Add to Google calendar invites
   - [ ] Tuesday Design System Meeting
      - [ ] not needed 
   - [ ] Tuesday BA meeting (if necessary)
      - [ ] not needed
   - [ ] Tuesday UX Research meeting (if necessary)
      - [ ] not needed
   - [ ] Thursday All-team meeting
- [ ] Google Drive
   - [ ] Add to drive as Contributor
- [ ] Roster
  - [ ] Send [link](https://docs.google.com/spreadsheets/d/1G6IgfvTdfnJRPbqxPkqfQ3dOSf8nvYqy0JVifhY6QdU/edit#gid=2054073727)
  - [ ] Team member adds themselves
  - [ ] Check for Public
- [ ] GitHub _- if it asks you to open up an authenticator app, use your GitHub password instead_
     - [ ] Add to team write team
     - [ ] Add to base/read team
     - [ ] Confirm that their name is on their Github  
     - [ ] Assign them to the issue #101, add them to role call and accountability check 
- [ ] Figma
  - [ ] invite
  - [ ] acceptance
- [ ] 1password
     - [ ] invitation (if necessary)
       - [ ] not needed 
     - [ ] acceptance
     - [ ] add to vaults
       - [ ] Incubator program (if necessary)
         - [ ] not needed 
       - [ ] incubator-UX  (if necessary)
         - [ ] not needed 
- [ ] Update team page on Wiki
   - [How to activate-inactivate team members from roster and wiki](https://github.com/hackforla/internship/wiki/How-to-activate-inactivate-team-members-from-roster-and-wiki)
- [ ] Add to email address(s)
   - [ ]ops@hackforla.org (if necessary)
      - [ ] not needed
- [ ] Train how to 
   - [ ] login to team email account (if necessary)
      - [ ] not needed
   - [ ] setup chrome shortcut for adding to desktop (if necessary)
      - [ ] not needed

**Comment by ExperimentsInHonesty** [comment]
#### Onboard Charles - PM 2023-11-12
- [ ] Slack channel membership
  - [ ] ```#Ops```
     - [ ] not needed
  - [ ] ```#Incubator```
- [ ] Add to Google calendar invites
  - [ ] Sunday PM Meeting   
  - [ ] Tuesday Project Leads Meeting
      - [ ] not needed 
  - [ ] Wednesday Ops Meeting
      - [ ] not needed
- [ ] Google Drive
   - [ ] Add to drive as Contributor
- [ ] Roster
  - [ ] Send [link](https://docs.google.com/spreadsheets/d/1kMuw8UWj3C4IebTwAmW3GluK2E1WcmUhsvyug0-kU_Y/edit#gid=0)
  - [ ] Team member adds themselves
  - [ ] Check for Public
- [ ] GitHub _- if it asks you to open up an authenticator app, use your GitHub password instead_
     - [ ] Add to team write team
     - [ ] Add to base/read team
     - [ ] Confirm that their name is on their Github  
     - [ ] Assign them to the issue #101, add them to role call and accountability check 
- [ ] Figma
  - [ ] invite
  - [ ] acceptance
- [ ] 1password
     - [ ] invitation (if necessary)
       - [ ] not needed 
     - [ ] acceptance
     - [ ] add to vaults
       - [ ] Incubator program (if necessary)
         - [ ] not needed 
       - [ ] incubator-UX  (if necessary)
         - [ ] not needed 
- [ ] Update team page on Wiki
   - [How to activate-inactivate team members from roster and wiki](https://github.com/hackforla/internship/wiki/How-to-activate-inactivate-team-members-from-roster-and-wiki)
- [ ] Add to email address(s)
   - [ ]ops@hackforla.org (if necessary)
      - [ ] not needed
- [ ] Train how to 
   - [ ] login to team email account (if necessary)
      - [ ] not needed
   - [ ] setup chrome shortcut for adding to desktop (if necessary)
      - [ ] not needed
